name: fermipy_calonly
channels:
  - fermi
  - conda-forge
dependencies:
  - python=3.9
  - fermitools=2.2.*
  - f2c>1.0
  - pyyaml
  - numpy>=1.16
  - scipy<1.14
  - astropy
  - matplotlib>=3.3
  - healpy
  - astropy-healpix
  - gammapy>=1.0
  - uproot